(ns frontend.modules.outliner.op
  "Build outliner ops"
  (:require [datascript.impl.entity :as de]))

(def ^:private ^:dynamic *outliner-ops*
  "Stores outliner ops that are generated by the following calls"
  nil)

(defn- op-transact!
  [result]
  (when (nil? *outliner-ops*)
    (throw (js/Error. (str (name (first result)) " not used in (transact! ...)"))))
  (conj! *outliner-ops* result)
  result)

(defn save-block!
  [block & {:as opts}]
  (op-transact!
   (when-let [block' (if (de/entity? block)
                       (assoc (.-kv ^js block) :db/id (:db/id block))
                       block)]
     [:save-block [block' opts]])))

(defn insert-blocks!
  [blocks target-block opts]
  (op-transact!
   (let [id (:db/id target-block)]
     [:insert-blocks [blocks id opts]])))

(defn delete-blocks!
  [blocks opts]
  (op-transact!
   (let [ids (map :db/id blocks)]
     (when (seq ids)
       [:delete-blocks [ids opts]]))))

(defn move-blocks!
  [blocks target-block opts]
  (op-transact!
   (let [ids (map :db/id blocks)
         target-id (:db/id target-block)]
     [:move-blocks [ids target-id opts]])))

(defn move-blocks-up-down!
  [blocks up?]
  (op-transact!
   (let [ids (map :db/id blocks)]
     [:move-blocks-up-down [ids up?]])))

(defn indent-outdent-blocks!
  [blocks indent? & {:as opts}]
  (op-transact!
   (let [ids (map :db/id blocks)]
     [:indent-outdent-blocks [ids indent? opts]])))

(defn transact!
  [tx-data tx-meta]
  (op-transact!
   [:transact [tx-data tx-meta]]))

(defn create-page!
  [title options]
  (op-transact!
   [:create-page [title options]]))

(defn rename-page!
  [page-uuid new-name]
  (op-transact!
   [:rename-page [page-uuid new-name]]))

(defn delete-page!
  [page-uuid]
  (op-transact!
   [:delete-page [page-uuid]]))
